### ISSUE TITLE
flat config

### ISSUE THREAD

**Issue by yukulele** [bfanger/eslint-plugin-only-warn#13]
Hi,
**eslint-plugin-only-warn** seems to not be compatible with the new [eslint flat config](https://eslint.org/docs/latest/use/configure/).

Is it possible to upgrade it?

Thanks!

**Comment by bfanger** [comment]
In my tests with ESLint 9.0.0 the "plugin" already compatible with the flat config.

I've updated the Readme on how to set it up.

It's different than other plugins as **eslint-plugin-only-warn** doesn't follow the ESLint spec as it cannot be expressed as processor or new rules.

It therfore patches the Linter, so just including the plugin is enough.

**Comment by sebastianrothe** [comment]
It also complies with the `compat` layer:

```js
// no need to import anything

// mimic CommonJS variables -- not needed if using CommonJS
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const compat = new FlatCompat({
    baseDirectory: __dirname,
    recommendedConfig: pluginJs.configs.recommended,
});

export default [
    ...compat.plugins("only-warn"),
];

```
