### ISSUE TITLE
feat: support only-error

### ISSUE THREAD

**Issue by AndersDJohnson** [bfanger/eslint-plugin-only-warn#2]
It would be nice if this plugin also supported setting all rules to errors. The name no longer makes a lot of sense but I think it would be better than writing a completely different plugin that would be so similar.

**Comment by bfanger** [comment]
This is outside the scope of this plugin.
In my opinion all codingstyle related issues should be treated as warnings as the code still executes.

But before I commit a gitHook runs: eslint --max-warnings 0
Which prevents sloppy coding.
