### ISSUE TITLE
Parsing errors are thrown as warnings

### ISSUE THREAD

**Issue by aminya** [bfanger/eslint-plugin-only-warn#6]
I think parsing errors should remain errors! Throwing warnings instead of errors for these will result in a broken script.

I like only-warn because it does not force me anything, but I expect the minimum safety from the linter.

**Comment by bfanger** [comment]
A parser error doesn't have to result in a broken script, a babel plugin could be ahead of eslint in converting some fancy new syntax.

But that edgecase aside, an eslint warning is also a strong indication something is wrong.

**Comment by aminya** [comment]
This is possible in my fork (`@aminya/eslint-plugin-only-warn`).
https://github.com/aminya/eslint-plugin-only-warn#fatal-as-warning

**Comment by bfanger** [comment]
Since 1.1.0 fatal errors are reported as errors
