### ISSUE TITLE
Exception to make errors for some rules

### ISSUE THREAD

**Issue by unlight** [bfanger/eslint-plugin-only-warn#8]
Since all rules are warnings only, we do not need `eslint-disable` to make exceptions (ci checks passes).
But for some rules (related to `eslint-disable`) I want to make exceptions - they must generate errors only:
- https://github.com/unlight/eslint-plugin-no-eslint-disable
- https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-abusive-eslint-disable.md
- https://github.com/edwardpayton/eslint-plugin-no-empty-disable

Is it possible to add exceptions as feature or it's out of scope?

**Comment by bfanger** [comment]
That is out-of-scope, the philosophy behind the plugin is that ESLint warnings and errors should be treated the same.
We run eslint with the [--max-warnings=0](https://eslint.org/docs/latest/user-guide/command-line-interface#--max-warnings) option, so CI won't allow _any_ linting violation (except the ones that  are explicitly allowed via an eslint-disable comment of course). 

In combination with the [Error Lens](https://marketplace.visualstudio.com/items?itemName=usernamehw.errorlens) vscode extension, which makes it harder to ignore and easier to spot and solve the warnings.

If you're not going to act on the the warnings, why enable the rule?

This philosophy is not for everyone, and there is a fork of this project that re-adds the ability to spend time on discussing and configuring rules as a warning or an error:
 https://github.com/aminya/eslint-plugin-only-warn
